import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gautam Mehta Portfolio",
  description: "Portfolio Generated By Next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black-600 min-h-screen">
      <body className={inter.className}>
        {children}</body>
    </html>
  );
}
